language: android
jdk: oraclejdk8
dist: trusty

android:
  components:
    - build-tools-29.0.2
    - android-29
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-x86-android-28



script:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - ./gradlew clean
  - ./gradlew assembleLiveDebug --stacktrace
  - ./gradlew detekt --stacktrace
  - ./gradlew feat_post_core:detekt --stacktrace
  - ./gradlew feat_post_ui:detekt --stacktrace
